COLOR_BLACK = "#000000"
COLOR_WHITE = "#FFFFFF"
COLOR_YELLOW = "#F0DBAF"
COLOR_BLUE = "#4EC7A2"
COLOR_BROWN = "#DECBA3"
COLOR_GRAY = "#464646"
COLOR_PINK1 = "#DC8686"
COLOR_PINK2 = "#B06161"
COLOR_PINK3 = "#E3A8A8"

FONT_MAIN = "JetBrainsMonoRoman"
FONT_WEIGHT_REGULAR = "normal"
FONT_WEIGHT_BOLD = "bold"


def FONT(font_size: int, name=FONT_MAIN, weight=FONT_WEIGHT_REGULAR):
  return (f"{name}", font_size, weight)
