name: ReleaseApp
on:
  push:
    branches: [master]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build for linux
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: add execution permissions to script
        run: chmod +x build_linux.sh

      - name: build project
        run: ./build_linux.sh
