name: ReleaseApp
on:
  push:
    branches: [master]
jobs:
  build_linux:
    name: Build for linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: add execution permissions to script
        run: chmod +x build_linux.sh

      - name: build project
        run: ./build_linux.sh

      - name: upload build
        uses: actions/upload-artifact@master
        with:
          name: linux-build
          path: linux-build.tar.gz

  release:
    name: Release project
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - name: download linux-build
        uses: actions/download-artifact@v1
        with:
          name: linux-build
          path: ./

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-build.tar.gz
          asset_name: linux-build.tar.gz
          asset_content_type: application/tar+gzip
